# Generated by Django 4.1.5 on 2023-01-30 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_snack_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
