# Generated by Django 4.1.5 on 2023-01-31 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_snack_create_at_snack_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
