# Generated by Django 4.1.5 on 2023-01-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_create_at_snack_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
